FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html styles.css app.js route-data.js dotwatcher-config.js leaflet.css leaflet.js modica-catania-fausto.gpx /usr/share/nginx/html/
